import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React, { ReactElement } from 'react';
import Providers from '@/app/components/providers/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactElement }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <div className="flex min-h-screen flex-col bg-primary">{children}</div>
        </body>
      </Providers>
    </html>
  );
}
